config/routes.rb
class ResqueWhitelistConstraint
  def initialize
    @whitelisted_users = %w(gjtorikian)
  end

  def matches?(request)
    return false unless user = request.env['warden'].user(:user)
    @whitelisted_users.include? user.login
  end
end

Branta::Application.routes.draw do
  post "/post_receive"         => "payload#create"
  get "/search"                => "search#index"

  if ENV['GITHUB_BRANTA_ORG_NAME'].nil?
    root 'application#index'

    get "/login"               => "sessions#create"
    get "/logout"              => "sessions#destroy"

    github_authenticated do
      get "/manage_webhook"      => "webhook#index"
      post '/webhook/create'     => "webhook#create"
      delete '/webhook/delete'   => "webhook#delete"
      mount Resque::Server.new, :at => "/resque", constraints: ResqueWhitelistConstraint.new
    end

  else
    github_authenticate(:org => ENV['GITHUB_BRANTA_ORG_NAME']) do
      root 'application#index'

      get "/login"               => "sessions#create"
      get "/logout"              => "sessions#destroy"

      get "/manage_webhook"      => "webhook#index"
      post '/webhook/create'     => "webhook#create"
      delete '/webhook/delete'   => "webhook#delete"

      mount Resque::Server.new, :at => "/resque"
    end
  end
end

app/views/elements/_blocked_org_landing.html.erb
<p class="center-block text-center">
  <img src="https://octodex.github.com/images/bouncercat.png" />
  Nope.
</p>

app/views/elements/_navbar.html.erb
<nav id="topnav" class="navbar navbar-default" role="navigation">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Branta", defined?(root_path) ? root_path : "#", class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <li>
          <a href="https://www.github.com/gjtorikian/branta"><%= octicon("mark-github", :title => "Source on GitHub", :'data-placement' => "bottom", :'data-toggle' => "tooltip").html_safe %></a>
        </li>
        <li class='about'>
          <%= link_to 'About', page_path('about') %>
        </li>
        <li class='donate'>
          <%= link_to 'Donate', page_path('donate') %>
        </li>
        <% if github_authenticated? %>
          <li class='manage'>
            <%= link_to 'Manage webhooks', manage_webhook_path %>
          </li>
        <% end %>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if github_authenticated? %>
          <li>
            <p class="navbar-text">
              <%= image_tag "https://github.com/#{github_user.login}.png", :size => "20x20", :alt => "Avatar for #{github_user.login}" %>
              <%= github_user.login %>
            </p>
          </li>
          <li><%= link_to((octicon("sign-out", :title => "Sign out", :'data-placement' => "bottom", :'data-toggle' => "tooltip")).html_safe, logout_path) %></li>
        <% else %>
          <li>
            <%= link_to("Sign in with GitHub", login_path) %>
          </li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div>
</nav>

app/views/elements/_non_org_landing.html.erb
<div id="hero" class="jumbotron">
  <div class="container">
    <div class="intro-heading">
        <h1>Branta</h1>
        <p class="lead">Push your site. Get it indexed. Search it instantly.</p>
    </div>
  </div>
</div>
<div class="container">
  <div class="row">
    <div class="col-md-4">
      <div class="numeric-point-wrapper">
        <span class="numeric-point">1</span>
        <p>Add a webhook to your repository that fires a <code><a href="https://developer.github.com/v3/activity/events/types/#pagebuildevent">PageBuildEvent</a></code>.</p>
      </div>
    </div>
    <div class="col-md-4">
      <div class="numeric-point-wrapper">
        <span class="numeric-point">2</span>
        <p>Make changes to your GitHub Pages site. Every site rebuild is reindexed for search.</p>
      </div>
   </div>
    <div class="col-md-4">
      <div class="numeric-point-wrapper">
        <span class="numeric-point">3</span>
        <p>Make an AJAX query to Branta and get your search results.</p>
      </div>
    </div>
  </div>
  <p class="center-block text-center">Branta respects your <em>sitemap.xml</em> and <em>robots.txt</em> files.</p>
</div>